version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: "iWXxcrkGhJN$$X"  # Escape $ with $$
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django_app:
    build: .
    env_file: .env  # Add this line to load variables
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
    volumes:
      - "/home/max/Desktop/fullfrom phone/newdjango_copy/static:/app/static"
      - "/home/max/Desktop/fullfrom phone/newdjango_copy/media:/app/media"
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn myproject.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - postgres
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - "/home/max/Desktop/fullfrom phone/newdjango_copy/static:/app/static"
      - "/home/max/Desktop/fullfrom phone/newdjango_copy/media:/app/media"
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - django_app
    restart: always

volumes:
  postgres_data: