# Generated by Django 5.1.5 on 2025-02-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_portfolioitem_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='portfolio/')),
                ('modal_id', models.SlugField(null=True, unique=True)),
                ('project_title', models.CharField(max_length=200)),
                ('intro_text', models.CharField(blank=True, max_length=200)),
                ('modal_image', models.ImageField(null=True, upload_to='portfolio/modals/')),
                ('description', models.TextField()),
                ('client', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
